/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignInRouteImport } from './routes/sign-in'
import { Route as IndexRouteImport } from './routes/index'
import { Route as WorkoutIndexRouteImport } from './routes/workout/index'
import { Route as HistoryIndexRouteImport } from './routes/history/index'
import { Route as ExercisesIndexRouteImport } from './routes/exercises/index'
import { Route as WorkoutActiveRouteImport } from './routes/workout/active'
import { Route as MesocycleSetupRouteImport } from './routes/mesocycle/setup'

const SignInRoute = SignInRouteImport.update({
  id: '/sign-in',
  path: '/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutIndexRoute = WorkoutIndexRouteImport.update({
  id: '/workout/',
  path: '/workout/',
  getParentRoute: () => rootRouteImport,
} as any)
const HistoryIndexRoute = HistoryIndexRouteImport.update({
  id: '/history/',
  path: '/history/',
  getParentRoute: () => rootRouteImport,
} as any)
const ExercisesIndexRoute = ExercisesIndexRouteImport.update({
  id: '/exercises/',
  path: '/exercises/',
  getParentRoute: () => rootRouteImport,
} as any)
const WorkoutActiveRoute = WorkoutActiveRouteImport.update({
  id: '/workout/active',
  path: '/workout/active',
  getParentRoute: () => rootRouteImport,
} as any)
const MesocycleSetupRoute = MesocycleSetupRouteImport.update({
  id: '/mesocycle/setup',
  path: '/mesocycle/setup',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/mesocycle/setup': typeof MesocycleSetupRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/mesocycle/setup': typeof MesocycleSetupRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/exercises': typeof ExercisesIndexRoute
  '/history': typeof HistoryIndexRoute
  '/workout': typeof WorkoutIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/sign-in': typeof SignInRoute
  '/mesocycle/setup': typeof MesocycleSetupRoute
  '/workout/active': typeof WorkoutActiveRoute
  '/exercises/': typeof ExercisesIndexRoute
  '/history/': typeof HistoryIndexRoute
  '/workout/': typeof WorkoutIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/sign-in'
    | '/mesocycle/setup'
    | '/workout/active'
    | '/exercises/'
    | '/history/'
    | '/workout/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/sign-in'
    | '/mesocycle/setup'
    | '/workout/active'
    | '/exercises'
    | '/history'
    | '/workout'
  id:
    | '__root__'
    | '/'
    | '/sign-in'
    | '/mesocycle/setup'
    | '/workout/active'
    | '/exercises/'
    | '/history/'
    | '/workout/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SignInRoute: typeof SignInRoute
  MesocycleSetupRoute: typeof MesocycleSetupRoute
  WorkoutActiveRoute: typeof WorkoutActiveRoute
  ExercisesIndexRoute: typeof ExercisesIndexRoute
  HistoryIndexRoute: typeof HistoryIndexRoute
  WorkoutIndexRoute: typeof WorkoutIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sign-in': {
      id: '/sign-in'
      path: '/sign-in'
      fullPath: '/sign-in'
      preLoaderRoute: typeof SignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/': {
      id: '/workout/'
      path: '/workout'
      fullPath: '/workout/'
      preLoaderRoute: typeof WorkoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/history/': {
      id: '/history/'
      path: '/history'
      fullPath: '/history/'
      preLoaderRoute: typeof HistoryIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/exercises/': {
      id: '/exercises/'
      path: '/exercises'
      fullPath: '/exercises/'
      preLoaderRoute: typeof ExercisesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/workout/active': {
      id: '/workout/active'
      path: '/workout/active'
      fullPath: '/workout/active'
      preLoaderRoute: typeof WorkoutActiveRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mesocycle/setup': {
      id: '/mesocycle/setup'
      path: '/mesocycle/setup'
      fullPath: '/mesocycle/setup'
      preLoaderRoute: typeof MesocycleSetupRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SignInRoute: SignInRoute,
  MesocycleSetupRoute: MesocycleSetupRoute,
  WorkoutActiveRoute: WorkoutActiveRoute,
  ExercisesIndexRoute: ExercisesIndexRoute,
  HistoryIndexRoute: HistoryIndexRoute,
  WorkoutIndexRoute: WorkoutIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
